/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedCategoriesRouteImport } from './routes/_authenticated/categories'
import { Route as AuthenticatedOnboardingIndexRouteImport } from './routes/_authenticated/onboarding/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedSettingsPasswordResetRouteImport } from './routes/_authenticated/settings/password-reset'
import { Route as AuthenticatedOnboardingCategoriesRouteImport } from './routes/_authenticated/onboarding/categories'
import { Route as AuthenticatedBudgetBudgetIdRouteImport } from './routes/_authenticated/budget/$budgetId'
import { Route as AuthenticatedOnboardingBudgetInfoRouteImport } from './routes/_authenticated/onboarding/budget/info'
import { Route as AuthenticatedOnboardingBudgetAllocateRouteImport } from './routes/_authenticated/onboarding/budget/allocate'
import { Route as AuthenticatedBudgetCreateInfoRouteImport } from './routes/_authenticated/budget/create/info'
import { Route as AuthenticatedBudgetCreateCategoriesRouteImport } from './routes/_authenticated/budget/create/categories'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCategoriesRoute = AuthenticatedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingIndexRoute =
  AuthenticatedOnboardingIndexRouteImport.update({
    id: '/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsPasswordResetRoute =
  AuthenticatedSettingsPasswordResetRouteImport.update({
    id: '/password-reset',
    path: '/password-reset',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedOnboardingCategoriesRoute =
  AuthenticatedOnboardingCategoriesRouteImport.update({
    id: '/onboarding/categories',
    path: '/onboarding/categories',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBudgetBudgetIdRoute =
  AuthenticatedBudgetBudgetIdRouteImport.update({
    id: '/budget/$budgetId',
    path: '/budget/$budgetId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingBudgetInfoRoute =
  AuthenticatedOnboardingBudgetInfoRouteImport.update({
    id: '/onboarding/budget/info',
    path: '/onboarding/budget/info',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingBudgetAllocateRoute =
  AuthenticatedOnboardingBudgetAllocateRouteImport.update({
    id: '/onboarding/budget/allocate',
    path: '/onboarding/budget/allocate',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBudgetCreateInfoRoute =
  AuthenticatedBudgetCreateInfoRouteImport.update({
    id: '/budget/create/info',
    path: '/budget/create/info',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBudgetCreateCategoriesRoute =
  AuthenticatedBudgetCreateCategoriesRouteImport.update({
    id: '/budget/create/categories',
    path: '/budget/create/categories',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/budget/$budgetId': typeof AuthenticatedBudgetBudgetIdRoute
  '/onboarding/categories': typeof AuthenticatedOnboardingCategoriesRoute
  '/settings/password-reset': typeof AuthenticatedSettingsPasswordResetRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/onboarding': typeof AuthenticatedOnboardingIndexRoute
  '/budget/create/categories': typeof AuthenticatedBudgetCreateCategoriesRoute
  '/budget/create/info': typeof AuthenticatedBudgetCreateInfoRoute
  '/onboarding/budget/allocate': typeof AuthenticatedOnboardingBudgetAllocateRoute
  '/onboarding/budget/info': typeof AuthenticatedOnboardingBudgetInfoRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/budget/$budgetId': typeof AuthenticatedBudgetBudgetIdRoute
  '/onboarding/categories': typeof AuthenticatedOnboardingCategoriesRoute
  '/settings/password-reset': typeof AuthenticatedSettingsPasswordResetRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/onboarding': typeof AuthenticatedOnboardingIndexRoute
  '/budget/create/categories': typeof AuthenticatedBudgetCreateCategoriesRoute
  '/budget/create/info': typeof AuthenticatedBudgetCreateInfoRoute
  '/onboarding/budget/allocate': typeof AuthenticatedOnboardingBudgetAllocateRoute
  '/onboarding/budget/info': typeof AuthenticatedOnboardingBudgetInfoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/categories': typeof AuthenticatedCategoriesRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/budget/$budgetId': typeof AuthenticatedBudgetBudgetIdRoute
  '/_authenticated/onboarding/categories': typeof AuthenticatedOnboardingCategoriesRoute
  '/_authenticated/settings/password-reset': typeof AuthenticatedSettingsPasswordResetRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/_authenticated/budget/create/categories': typeof AuthenticatedBudgetCreateCategoriesRoute
  '/_authenticated/budget/create/info': typeof AuthenticatedBudgetCreateInfoRoute
  '/_authenticated/onboarding/budget/allocate': typeof AuthenticatedOnboardingBudgetAllocateRoute
  '/_authenticated/onboarding/budget/info': typeof AuthenticatedOnboardingBudgetInfoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/categories'
    | '/expenses'
    | '/settings'
    | '/'
    | '/budget/$budgetId'
    | '/onboarding/categories'
    | '/settings/password-reset'
    | '/api/auth/$'
    | '/onboarding'
    | '/budget/create/categories'
    | '/budget/create/info'
    | '/onboarding/budget/allocate'
    | '/onboarding/budget/info'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/categories'
    | '/expenses'
    | '/settings'
    | '/'
    | '/budget/$budgetId'
    | '/onboarding/categories'
    | '/settings/password-reset'
    | '/api/auth/$'
    | '/onboarding'
    | '/budget/create/categories'
    | '/budget/create/info'
    | '/onboarding/budget/allocate'
    | '/onboarding/budget/info'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/categories'
    | '/_authenticated/expenses'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/budget/$budgetId'
    | '/_authenticated/onboarding/categories'
    | '/_authenticated/settings/password-reset'
    | '/api/auth/$'
    | '/_authenticated/onboarding/'
    | '/_authenticated/budget/create/categories'
    | '/_authenticated/budget/create/info'
    | '/_authenticated/onboarding/budget/allocate'
    | '/_authenticated/onboarding/budget/info'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/categories': {
      id: '/_authenticated/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/': {
      id: '/_authenticated/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/password-reset': {
      id: '/_authenticated/settings/password-reset'
      path: '/password-reset'
      fullPath: '/settings/password-reset'
      preLoaderRoute: typeof AuthenticatedSettingsPasswordResetRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/onboarding/categories': {
      id: '/_authenticated/onboarding/categories'
      path: '/onboarding/categories'
      fullPath: '/onboarding/categories'
      preLoaderRoute: typeof AuthenticatedOnboardingCategoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/budget/$budgetId': {
      id: '/_authenticated/budget/$budgetId'
      path: '/budget/$budgetId'
      fullPath: '/budget/$budgetId'
      preLoaderRoute: typeof AuthenticatedBudgetBudgetIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/budget/info': {
      id: '/_authenticated/onboarding/budget/info'
      path: '/onboarding/budget/info'
      fullPath: '/onboarding/budget/info'
      preLoaderRoute: typeof AuthenticatedOnboardingBudgetInfoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/budget/allocate': {
      id: '/_authenticated/onboarding/budget/allocate'
      path: '/onboarding/budget/allocate'
      fullPath: '/onboarding/budget/allocate'
      preLoaderRoute: typeof AuthenticatedOnboardingBudgetAllocateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/budget/create/info': {
      id: '/_authenticated/budget/create/info'
      path: '/budget/create/info'
      fullPath: '/budget/create/info'
      preLoaderRoute: typeof AuthenticatedBudgetCreateInfoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/budget/create/categories': {
      id: '/_authenticated/budget/create/categories'
      path: '/budget/create/categories'
      fullPath: '/budget/create/categories'
      preLoaderRoute: typeof AuthenticatedBudgetCreateCategoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsPasswordResetRoute: typeof AuthenticatedSettingsPasswordResetRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsPasswordResetRoute:
    AuthenticatedSettingsPasswordResetRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedCategoriesRoute: typeof AuthenticatedCategoriesRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedBudgetBudgetIdRoute: typeof AuthenticatedBudgetBudgetIdRoute
  AuthenticatedOnboardingCategoriesRoute: typeof AuthenticatedOnboardingCategoriesRoute
  AuthenticatedOnboardingIndexRoute: typeof AuthenticatedOnboardingIndexRoute
  AuthenticatedBudgetCreateCategoriesRoute: typeof AuthenticatedBudgetCreateCategoriesRoute
  AuthenticatedBudgetCreateInfoRoute: typeof AuthenticatedBudgetCreateInfoRoute
  AuthenticatedOnboardingBudgetAllocateRoute: typeof AuthenticatedOnboardingBudgetAllocateRoute
  AuthenticatedOnboardingBudgetInfoRoute: typeof AuthenticatedOnboardingBudgetInfoRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCategoriesRoute: AuthenticatedCategoriesRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedBudgetBudgetIdRoute: AuthenticatedBudgetBudgetIdRoute,
  AuthenticatedOnboardingCategoriesRoute:
    AuthenticatedOnboardingCategoriesRoute,
  AuthenticatedOnboardingIndexRoute: AuthenticatedOnboardingIndexRoute,
  AuthenticatedBudgetCreateCategoriesRoute:
    AuthenticatedBudgetCreateCategoriesRoute,
  AuthenticatedBudgetCreateInfoRoute: AuthenticatedBudgetCreateInfoRoute,
  AuthenticatedOnboardingBudgetAllocateRoute:
    AuthenticatedOnboardingBudgetAllocateRoute,
  AuthenticatedOnboardingBudgetInfoRoute:
    AuthenticatedOnboardingBudgetInfoRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
