
export const defaultCategories = [
  { key: 'rent', label: 'Rent', icon: '🏠' },
  { key: 'groceries', label: 'Groceries', icon: '🛒' },
  { key: 'eat-out-takeaways', label: 'Eat Out & Takeaways', icon: '🍽️' },
  { key: 'transport-fuel', label: 'Transport & Fuel', icon: '🚗' },
  { key: 'medical', label: 'Medical', icon: '⚕️' },
  { key: 'personal-care', label: 'Personal Care', icon: '🧴' },
  { key: 'utilities', label: 'Utilities', icon: '💡' },
  { key: 'entertainment', label: 'Entertainment', icon: '🎮' },
  { key: 'home-garden', label: 'Home & Garden', icon: '🏡' },
  { key: 'software-and-services', label: 'Software & Services', icon: '💻' },
  { key: 'pets', label: 'Pets', icon: '🐕' },
  { key: 'phone-internet', label: 'Phone & Internet', icon: '📱' },
  { key: 'savings', label: 'Savings', icon: '💰' },
  { key: 'investments', label: 'Investments', icon: '📈' },
  { key: 'housekeeping', label: 'Housekeeping', icon: '🧹' },
  { key: 'coffee', label: 'Coffee', icon: '☕' },
  { key: 'insurance', label: 'Insurance', icon: '🛡️' },
  { key: 'clothing', label: 'Clothing', icon: '👕' },
  { key: 'business', label: 'Business', icon: '💼' },
  { key: 'cash', label: 'Cash', icon: '💵' },
  { key: 'general-purchases', label: 'General Purchases', icon: '🛍️' },
  { key: 'parking', label: 'Parking', icon: '🅿️' },
  { key: 'books-stationary', label: 'Books & Stationary', icon: '📚' },
  { key: 'alcohol', label: 'Alcohol', icon: '🍺' },
  { key: 'bank-fees', label: 'Bank Fees', icon: '🏦' },
  { key: 'exception', label: 'Exception', icon: '⚠️' },
  { key: 'christmas-savings', label: 'Christmas Savings', icon: '🎄' },
  { key: 'travel-savings', label: 'Travel Savings', icon: '✈️' },
] as const;
