// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID                    uuid.UUID
	AccountID             uuid.UUID
	UserID                uuid.UUID
	AccessToken           sql.NullString
	RefreshToken          sql.NullString
	IDToken               sql.NullString
	AccessTokenExpiresAt  sql.NullTime
	RefreshTokenExpiresAt sql.NullTime
	Scope                 sql.NullString
	Password              sql.NullString
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type Budget struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Name          string
	StartAmount   string
	CurrentAmount string
	IsActive      bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     sql.NullTime
	SaIv          sql.NullString
	SaTag         sql.NullString
	CaIv          sql.NullString
	CaTag         sql.NullString
	StartDate     sql.NullTime
	EndDate       sql.NullTime
}

type BudgetRecurringExpense struct {
	ID          uuid.UUID
	BudgetID    uuid.UUID
	Description string
	Amount      string
	CategoryID  uuid.NullUUID
	IsPaid      bool
	ExpenseID   uuid.NullUUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
	TemplateID  uuid.NullUUID
	ScheduledAt sql.NullString
}

type Category struct {
	ID        uuid.UUID
	Key       string
	Label     string
	Icon      string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type CategoryBudget struct {
	ID              uuid.UUID
	BudgetID        uuid.UUID
	CategoryID      uuid.UUID
	AllocatedAmount string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       sql.NullTime
}

type Chat struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	ChatID    sql.NullString
	Type      sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Expense struct {
	ID          uuid.UUID
	BudgetID    uuid.UUID
	Description string
	Amount      string
	CategoryID  uuid.NullUUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
	Note        sql.NullString
	TemplateID  uuid.NullUUID
}

type Notification struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Message   string
	Channel   string
	SentAt    sql.NullTime
	CreatedAt time.Time
	Type      string
}

type NotificationPreference struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Type        string
	Enabled     bool
	Channel     string
	ScheduledAt sql.NullTime
	CreatedAt   time.Time
	UpdatedAt   time.Time
	EntityID    uuid.NullUUID
}

type RecurringExpenseTemplate struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Description string
	Amount      string
	CategoryID  uuid.NullUUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
	ScheduledAt string
}

type Session struct {
	ID        uuid.UUID
	ExpiresAt time.Time
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	IpAddress sql.NullString
	UserAgent sql.NullString
	UserID    uuid.UUID
}

type User struct {
	ID            uuid.UUID
	Name          string
	Email         string
	EmailVerified bool
	Image         sql.NullString
	Onboarded     bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type UserActivity struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Date      time.Time
	Count     int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type UserCategory struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	CategoryID uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	DeletedAt  sql.NullTime
}

type UserPreference struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	BudgetStartDate sql.NullInt32
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Frequency       sql.NullString
	CustomDuration  sql.NullInt32
}

type Verification struct {
	ID         uuid.UUID
	Identifier string
	Value      string
	ExpiresAt  time.Time
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}
