/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as ProfileRecurringExpensesRouteImport } from './routes/profile.recurring-expenses'
import { Route as ProfilePreferencesRouteImport } from './routes/profile.preferences'
import { Route as ProfilePennyBotRouteImport } from './routes/profile.penny-bot'
import { Route as ProfileNotificationsRouteImport } from './routes/profile.notifications'
import { Route as ProfileMcpTokenRouteImport } from './routes/profile.mcp-token'
import { Route as CategoriesIdRouteImport } from './routes/categories/$id'
import { Route as BudgetsNewRouteImport } from './routes/budgets/new'
import { Route as BudgetsIdRouteImport } from './routes/budgets/$id'
import { Route as BudgetsIdIndexRouteImport } from './routes/budgets/$id.index'
import { Route as BudgetsIdExpensesRouteImport } from './routes/budgets/$id.expenses'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileRecurringExpensesRoute =
  ProfileRecurringExpensesRouteImport.update({
    id: '/recurring-expenses',
    path: '/recurring-expenses',
    getParentRoute: () => ProfileRoute,
  } as any)
const ProfilePreferencesRoute = ProfilePreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfilePennyBotRoute = ProfilePennyBotRouteImport.update({
  id: '/penny-bot',
  path: '/penny-bot',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileNotificationsRoute = ProfileNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileMcpTokenRoute = ProfileMcpTokenRouteImport.update({
  id: '/mcp-token',
  path: '/mcp-token',
  getParentRoute: () => ProfileRoute,
} as any)
const CategoriesIdRoute = CategoriesIdRouteImport.update({
  id: '/categories/$id',
  path: '/categories/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsNewRoute = BudgetsNewRouteImport.update({
  id: '/budgets/new',
  path: '/budgets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsIdRoute = BudgetsIdRouteImport.update({
  id: '/budgets/$id',
  path: '/budgets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsIdIndexRoute = BudgetsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BudgetsIdRoute,
} as any)
const BudgetsIdExpensesRoute = BudgetsIdExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => BudgetsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRouteWithChildren
  '/register': typeof RegisterRoute
  '/budgets/$id': typeof BudgetsIdRouteWithChildren
  '/budgets/new': typeof BudgetsNewRoute
  '/categories/$id': typeof CategoriesIdRoute
  '/profile/mcp-token': typeof ProfileMcpTokenRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/penny-bot': typeof ProfilePennyBotRoute
  '/profile/preferences': typeof ProfilePreferencesRoute
  '/profile/recurring-expenses': typeof ProfileRecurringExpensesRoute
  '/profile/': typeof ProfileIndexRoute
  '/budgets/$id/expenses': typeof BudgetsIdExpensesRoute
  '/budgets/$id/': typeof BudgetsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/budgets/new': typeof BudgetsNewRoute
  '/categories/$id': typeof CategoriesIdRoute
  '/profile/mcp-token': typeof ProfileMcpTokenRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/penny-bot': typeof ProfilePennyBotRoute
  '/profile/preferences': typeof ProfilePreferencesRoute
  '/profile/recurring-expenses': typeof ProfileRecurringExpensesRoute
  '/profile': typeof ProfileIndexRoute
  '/budgets/$id/expenses': typeof BudgetsIdExpensesRoute
  '/budgets/$id': typeof BudgetsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRouteWithChildren
  '/register': typeof RegisterRoute
  '/budgets/$id': typeof BudgetsIdRouteWithChildren
  '/budgets/new': typeof BudgetsNewRoute
  '/categories/$id': typeof CategoriesIdRoute
  '/profile/mcp-token': typeof ProfileMcpTokenRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/penny-bot': typeof ProfilePennyBotRoute
  '/profile/preferences': typeof ProfilePreferencesRoute
  '/profile/recurring-expenses': typeof ProfileRecurringExpensesRoute
  '/profile/': typeof ProfileIndexRoute
  '/budgets/$id/expenses': typeof BudgetsIdExpensesRoute
  '/budgets/$id/': typeof BudgetsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/budgets/$id'
    | '/budgets/new'
    | '/categories/$id'
    | '/profile/mcp-token'
    | '/profile/notifications'
    | '/profile/penny-bot'
    | '/profile/preferences'
    | '/profile/recurring-expenses'
    | '/profile/'
    | '/budgets/$id/expenses'
    | '/budgets/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/budgets/new'
    | '/categories/$id'
    | '/profile/mcp-token'
    | '/profile/notifications'
    | '/profile/penny-bot'
    | '/profile/preferences'
    | '/profile/recurring-expenses'
    | '/profile'
    | '/budgets/$id/expenses'
    | '/budgets/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/budgets/$id'
    | '/budgets/new'
    | '/categories/$id'
    | '/profile/mcp-token'
    | '/profile/notifications'
    | '/profile/penny-bot'
    | '/profile/preferences'
    | '/profile/recurring-expenses'
    | '/profile/'
    | '/budgets/$id/expenses'
    | '/budgets/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  BudgetsIdRoute: typeof BudgetsIdRouteWithChildren
  BudgetsNewRoute: typeof BudgetsNewRoute
  CategoriesIdRoute: typeof CategoriesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/recurring-expenses': {
      id: '/profile/recurring-expenses'
      path: '/recurring-expenses'
      fullPath: '/profile/recurring-expenses'
      preLoaderRoute: typeof ProfileRecurringExpensesRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/preferences': {
      id: '/profile/preferences'
      path: '/preferences'
      fullPath: '/profile/preferences'
      preLoaderRoute: typeof ProfilePreferencesRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/penny-bot': {
      id: '/profile/penny-bot'
      path: '/penny-bot'
      fullPath: '/profile/penny-bot'
      preLoaderRoute: typeof ProfilePennyBotRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/notifications': {
      id: '/profile/notifications'
      path: '/notifications'
      fullPath: '/profile/notifications'
      preLoaderRoute: typeof ProfileNotificationsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/mcp-token': {
      id: '/profile/mcp-token'
      path: '/mcp-token'
      fullPath: '/profile/mcp-token'
      preLoaderRoute: typeof ProfileMcpTokenRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/categories/$id': {
      id: '/categories/$id'
      path: '/categories/$id'
      fullPath: '/categories/$id'
      preLoaderRoute: typeof CategoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets/new': {
      id: '/budgets/new'
      path: '/budgets/new'
      fullPath: '/budgets/new'
      preLoaderRoute: typeof BudgetsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets/$id': {
      id: '/budgets/$id'
      path: '/budgets/$id'
      fullPath: '/budgets/$id'
      preLoaderRoute: typeof BudgetsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets/$id/': {
      id: '/budgets/$id/'
      path: '/'
      fullPath: '/budgets/$id/'
      preLoaderRoute: typeof BudgetsIdIndexRouteImport
      parentRoute: typeof BudgetsIdRoute
    }
    '/budgets/$id/expenses': {
      id: '/budgets/$id/expenses'
      path: '/expenses'
      fullPath: '/budgets/$id/expenses'
      preLoaderRoute: typeof BudgetsIdExpensesRouteImport
      parentRoute: typeof BudgetsIdRoute
    }
  }
}

interface ProfileRouteChildren {
  ProfileMcpTokenRoute: typeof ProfileMcpTokenRoute
  ProfileNotificationsRoute: typeof ProfileNotificationsRoute
  ProfilePennyBotRoute: typeof ProfilePennyBotRoute
  ProfilePreferencesRoute: typeof ProfilePreferencesRoute
  ProfileRecurringExpensesRoute: typeof ProfileRecurringExpensesRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileMcpTokenRoute: ProfileMcpTokenRoute,
  ProfileNotificationsRoute: ProfileNotificationsRoute,
  ProfilePennyBotRoute: ProfilePennyBotRoute,
  ProfilePreferencesRoute: ProfilePreferencesRoute,
  ProfileRecurringExpensesRoute: ProfileRecurringExpensesRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface BudgetsIdRouteChildren {
  BudgetsIdExpensesRoute: typeof BudgetsIdExpensesRoute
  BudgetsIdIndexRoute: typeof BudgetsIdIndexRoute
}

const BudgetsIdRouteChildren: BudgetsIdRouteChildren = {
  BudgetsIdExpensesRoute: BudgetsIdExpensesRoute,
  BudgetsIdIndexRoute: BudgetsIdIndexRoute,
}

const BudgetsIdRouteWithChildren = BudgetsIdRoute._addFileChildren(
  BudgetsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRouteWithChildren,
  RegisterRoute: RegisterRoute,
  BudgetsIdRoute: BudgetsIdRouteWithChildren,
  BudgetsNewRoute: BudgetsNewRoute,
  CategoriesIdRoute: CategoriesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
