/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BudgetsNewRouteImport } from './routes/budgets/new'
import { Route as BudgetsIdRouteImport } from './routes/budgets/$id'
import { Route as BudgetsIdIndexRouteImport } from './routes/budgets/$id.index'
import { Route as BudgetsIdExpensesRouteImport } from './routes/budgets/$id.expenses'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsNewRoute = BudgetsNewRouteImport.update({
  id: '/budgets/new',
  path: '/budgets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsIdRoute = BudgetsIdRouteImport.update({
  id: '/budgets/$id',
  path: '/budgets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsIdIndexRoute = BudgetsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BudgetsIdRoute,
} as any)
const BudgetsIdExpensesRoute = BudgetsIdExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => BudgetsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/budgets/$id': typeof BudgetsIdRouteWithChildren
  '/budgets/new': typeof BudgetsNewRoute
  '/budgets/$id/expenses': typeof BudgetsIdExpensesRoute
  '/budgets/$id/': typeof BudgetsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/budgets/new': typeof BudgetsNewRoute
  '/budgets/$id/expenses': typeof BudgetsIdExpensesRoute
  '/budgets/$id': typeof BudgetsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/budgets/$id': typeof BudgetsIdRouteWithChildren
  '/budgets/new': typeof BudgetsNewRoute
  '/budgets/$id/expenses': typeof BudgetsIdExpensesRoute
  '/budgets/$id/': typeof BudgetsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/budgets/$id'
    | '/budgets/new'
    | '/budgets/$id/expenses'
    | '/budgets/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/budgets/new'
    | '/budgets/$id/expenses'
    | '/budgets/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/budgets/$id'
    | '/budgets/new'
    | '/budgets/$id/expenses'
    | '/budgets/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  BudgetsIdRoute: typeof BudgetsIdRouteWithChildren
  BudgetsNewRoute: typeof BudgetsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets/new': {
      id: '/budgets/new'
      path: '/budgets/new'
      fullPath: '/budgets/new'
      preLoaderRoute: typeof BudgetsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets/$id': {
      id: '/budgets/$id'
      path: '/budgets/$id'
      fullPath: '/budgets/$id'
      preLoaderRoute: typeof BudgetsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets/$id/': {
      id: '/budgets/$id/'
      path: '/'
      fullPath: '/budgets/$id/'
      preLoaderRoute: typeof BudgetsIdIndexRouteImport
      parentRoute: typeof BudgetsIdRoute
    }
    '/budgets/$id/expenses': {
      id: '/budgets/$id/expenses'
      path: '/expenses'
      fullPath: '/budgets/$id/expenses'
      preLoaderRoute: typeof BudgetsIdExpensesRouteImport
      parentRoute: typeof BudgetsIdRoute
    }
  }
}

interface BudgetsIdRouteChildren {
  BudgetsIdExpensesRoute: typeof BudgetsIdExpensesRoute
  BudgetsIdIndexRoute: typeof BudgetsIdIndexRoute
}

const BudgetsIdRouteChildren: BudgetsIdRouteChildren = {
  BudgetsIdExpensesRoute: BudgetsIdExpensesRoute,
  BudgetsIdIndexRoute: BudgetsIdIndexRoute,
}

const BudgetsIdRouteWithChildren = BudgetsIdRoute._addFileChildren(
  BudgetsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  BudgetsIdRoute: BudgetsIdRouteWithChildren,
  BudgetsNewRoute: BudgetsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
